# Generated by Django 5.0.1 on 2024-01-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0007_item_rented_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="rented_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
