# Generated by Django 5.0.1 on 2024-01-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0009_itemdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemdetail",
            name="price",
            field=models.FloatField(default=0.0),
        ),
    ]
